### ISSUE TITLE
Редактирование ссылок

### ISSUE THREAD

**Issue by stopdesign** [fbkinfo/sir-trevor-js#2]
Нужна возможность редактировать ссылки, поставленные в блоках. При выделении существующей ссылки клик на кнопку «ссылка» должен приводить к появлению такого же диалога, но с заполненным значением, чтобы его можно было изменить:
![картинка](https://cloud.githubusercontent.com/assets/244666/7272147/6041ca0a-e8f1-11e4-9d87-708761de280c.jpg)

**Comment by punund** [comment]
This functionality is already present.

---

Это и так работает.
