### ISSUE TITLE
Сделать у ссылок подсказку с адресом

### ISSUE THREAD

**Issue by stopdesign** [fbkinfo/sir-trevor-js#3]
У всех ссылок должна быть всплывающая подсказка с адресом (адрес является ссылкой с target="_blank"). Если адрес адской длины, то пусть разбивается на строки (в css настраивается).
![screen shot 2015-04-22 at 13 16 10](https://cloud.githubusercontent.com/assets/244666/7272203/da97ee60-e8f1-11e4-9621-8f432c83722c.jpg)

**Comment by punund** [comment]
Done by inegrating https://github.com/andrewplummer/tooltip into the code.
Thanks go to @andrewplummer.
Long links are not wrapped, but truncated instead.
